fw:
  - name: aux
    windows:
    - window_name: main
      cwd: ~/

  - name: trx
    windows:
    - window_name: TRX
      cwd: ~/work/priv/TRX/

  - name: wind_garden
    windows:
    - window_name: main
      cwd: ~/work/priv/wind.garden/

  - name: trcustoms
    windows:
    - window_name: main
      cwd: ~/work/priv/trcustoms/

  - name: nordhealth
    windows:
    - window_name: kraken-main
      cwd: ~/work/nordhealth/kraken/
